name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"       # daily at midnight UTC
  workflow_dispatch:
  push:
    branches: ["master", "main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write         # to commit the SVG/MD back
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Use your PAT here for full org access
          token: ${{ secrets.METRICS_TOKEN }}

          # Target your organization
          user: Augmented-Perception

          # Layout & timezone
          template: classic
          base: header, introduction, community, repositories, metadata
          config_timezone: Europe/London

          # Org-level plugins
          plugin_activity: yes
          plugin_activity_days: 30
          plugin_activity_visibility: all

          plugin_repositories: yes
          plugin_repositories_limit: 10

          plugin_community: yes

          plugin_notable: yes
          plugin_notable_from: organization

          plugin_stars: yes
          plugin_stars_limit: 5

          plugin_traffic: yes

          plugin_languages: yes
          plugin_languages_limit: 8

          # Disable user-specific metrics
          plugin_achievements: no
          plugin_leetcode: no
          plugin_wakatime: no
          plugin_habits: no
          plugin_16personalities: no
          plugin_sponsorships: no
          plugin_sponsors: no
