name: Metrics
on:
  schedule:
    - cron: "0 0 * * 1"       # Every Monday at midnight UTC
  workflow_dispatch:
  push:
    branches: ["master", "main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write         # to commit the SVG/MD back
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Target your organization
          user: Augmented-Perception

          # Layout & timezone
          template: classic
          base: header, introduction, community, repositories, metadata
          config_timezone: Europe/London

          # Org-level plugins
          plugin_activity: yes
          plugin_activity_days: 30
          plugin_activity_visibility: all

          # Introduction
          plugin_introduction: yes
          plugin_introduction_title: yes

          plugin_repositories: yes

          plugin_traffic: yes

          plugin_languages: yes
          plugin_languages_limit: 8

          plugin_sponsors: yes
